name: Test workflow
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Trigger
      id: Trigger
      uses: ormbo/trigger-workflow/.github/action@main
      with:
        workflow_file: trigger_by.yml
        repo: trigger-workflow
        owner: ormbo
        branch: ${{ github.ref_name }}
        token: ${{ secrets.TRIGGER_SECRET }}

    
    - name: print
      run:
        echo '${{ steps.Trigger.outputs.myOutput }}'