name: Test workflow
on:
    workflow_dispatch:


permissions:
  actions: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:


    - name: Trigger
      id: Trigger
      uses: ormbo/trigger-workflow/.github/action@main
      with:
        workflow_file: trigger_by.yml
        repo: trigger-workflow
        owner: ormbo
        inputs: '{"target_user": "Or", "environment": "dev", "debug_mode": true}'
        branch: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        wait_until: true

    
    - name: print
      run:
        echo '${{ steps.Trigger.outputs.myOutput }}'