name: Test workflow
on:
    workflow_dispatch:
        inputs:
            workflow_file:
                description: 'Test the workflow'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ormbo/trigger-workflow/.github/action@main
      with:
        workflow_file: ${{ inputs.workflow_file }}