name: Trigger BY
on:
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
        
    
    - name: print
      run: | 
            DURATION=300 
            END_TIME=$((SECONDS + DURATION))

            echo "Loop starting at $(date +%T) for $DURATION seconds."

            while [ $SECONDS -lt $END_TIME ]; do
                echo "Executing command at $(date +%T)" 
            done

            echo "Loop finished at $(date +%T)."
