name: Manual Input Demo
run-name: Workflow - ${{ inputs.CorrelationID}}

on:
  workflow_dispatch:
    inputs:
      # 1. String Input
      target_user:
        description: 'Who are we greeting?'
        required: true
        default: 'World'
        type: string
      
      # 2. Choice/Dropdown Input
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      
      # 3. Boolean/Checkbox Input
      debug_mode:
        description: 'Enable Debug Logs?'
        required: false
        default: false
        type: boolean

      CorrelationID:
        description: 'Correlation ID for tracking'
        required: false
        type: string
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "üëã Hello, ${{ inputs.target_user }}!"
          echo "üåç Environment selected: ${{ inputs.environment }}"
          echo "üêõ Debug Mode status: ${{ inputs.debug_mode }}"

      - name: Test Debug Mode
        shell: python
        run: |
          import time

          while True:
              print("Running workflow... ")
              time.sleep(5)
              print("Running workflow... ")
              sleep(5)
              break
